export const FETCH_ALBUMS = 'FETCH_ALBUMS'
export const FETCH_ALBUMS_SUCCESS = 'FETCH_ALBUMS_SUCCESS'
export const FETCH_ALBUMS_FAILED = 'FETCH_ALBUMS_FAILED'

export const CREATE_ALBUMS = 'CREATE_ALBUMS'
export const CREATE_ALBUMS_SUCCESS = 'CREATE_ALBUMS_SUCCESS'
export const CREATE_ALBUMS_FAILED = 'CREATE_ALBUMS_FAILED'
